# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  identifier = "home"
  name = "Home"
  url = "/en/"
  weight = 10

[[main]]
  identifier = "research"
  name = "Research"
  url = "/en/research/"
  weight = 20

[[main]]
  identifier = "publications"
  name = "Publications"
  url = "/en/publication/"
  weight = 30

[[main]]
  identifier = "software"
  name = "Software"
  url = "/en/software/"
  weight = 40

[[main]]
  identifier = "talks"
  name = "Talks"
  url = "/en/talk/"
  weight = 50

[[main]]
  identifier = "teaching"
  name = "Teaching"
  url = "/en/teaching/"
  weight = 60

[[main]]
  identifier = "contact"
  name = "Contact"
  url = "/en/contact/"
  weight = 70

[[main]]
  identifier = "cv"
  name = "CV"
  # url = "/files/CV_MLATIF_FR.pdf"
  weight = 80

[[main]]
  identifier = "cv_fr"
  parent = "cv"
  name = "CV - English"
  url =  "/project/default_soon/"         #"/files/CV_MLATIF_EN.pdf"
  weight = 90

[[main]]
  identifier = "cv_en"
  parent = "cv"
  name = "CV - French"
  url = "/files/cv_mlatif_fr.pdf"
  weight = 100

#############################################################
#############################################################
#############################################################
#############################################################

  #[[main]]
  #  name = "Home"
  #  url = "#about"
  #  weight = 10

  # [[main]]
  #   name = "Publications"
  #   url = "#featured"
  #   weight = 60


# [[main]]
#   name = "Compétences"
#   url = "#skills"
#   weight = 50

  # [[main]]
  #   name = "Posts"
  #   url = "#posts"
  #   weight = 20

  # Link to a PDF of your resume/CV from the menu.
  # To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
  # [[main]]
  #    name = "CV"
  #    url = "files/cv.pdf"
  #    weight = 70
