# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  identifier = "education"
  name = "Formation"
  url = "#education"
  weight = 10

[[main]]
  identifier = "experience"
  name = "Experience"
  url = "#experience"
  weight = 20

[[main]]
  identifier = "project"
  name = "Projets & Publications"
  url = "#projects"
  weight = 30

[[main]]
  identifier = "CV_DOCS"
  name = "CV & Portfolio"
  # url = "files/CV_LM.pdf"
  weight = 40

[[main]]
  identifier = "CV_FR"
  parent = "CV_DOCS"
  name = "CV - Français"
  url = "files/CV_LM.pdf"
  weight = 45
[[main]]
  identifier = "CV_EN"
  parent = "CV_DOCS"
  name = "CV - Anglais"
  url = "/project/default_soon/"
  weight = 55
[[main]]
  identifier = "PF_PHD"
  parent = "CV_DOCS"
  name = "Portfolio"
  url = "/project/default_soon/"
  weight = 65

  #[[main]]
  #  name = "Home"
  #  url = "#about"
  #  weight = 10

  # [[main]]
  #   name = "Publications"
  #   url = "#featured"
  #   weight = 60

  # [[main]]
  #   name = "Contact"
  #   url = "#contact"
  #   weight = 40

# [[main]]
#   name = "Compétences"
#   url = "#skills"
#   weight = 50

  # [[main]]
  #   name = "Posts"
  #   url = "#posts"
  #   weight = 20

  # Link to a PDF of your resume/CV from the menu.
  # To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
  # [[main]]
  #    name = "CV"
  #    url = "files/cv.pdf"
  #    weight = 70
